### ISSUE TITLE
pre-commit hook does not work for .pyi files

### ISSUE THREAD

**Issue by proofit404** [asottile/reorder_python_imports#103]
Hi, thanks for the awesome project!

It very similar to https://github.com/psf/black/issues/402

As a workaround, I use a similar approach with `files` and empty `types`.

```yaml
  - repo: https://github.com/asottile/reorder_python_imports
    rev: ''
    hooks:
      - id: reorder-python-imports
        args: [--application-directories=.:src:tests/helpers]
        exclude: migrations
        files: \.pyi?$
        types: []
```

Have a good day :tada:

Best regards,
Artem.
