### ISSUE TITLE
Different behavior running locally or on docker

### ISSUE THREAD

**Issue by emanuele-leopardi** [asottile/reorder_python_imports#198]
Hello sometimes I'm getting different behaviour depending on when this , as part of pre-commit, is running.

- Mac Big Sur 11.2 ( not M1) 
```
python 3.9.7
``` 
```
- repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
```
```
pre-commit 2.15.0
```

```
import os

import yaml
from cdktf import App
from cdktf import AzurermBackend
from cdktf import TerraformStack
from constructs import Construct

from imports.github import DataGithubTeam
from imports.github import GithubProvider
from imports.github import Repository
from imports.github import TeamRepository
```

- Docker cimg/python:3.9 ( used on circle-ci build) ( Based on Ubuntu 20.04.2 LTS)
```
python 3.9.7
``` 
```
- repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
```
```
pre-commit 2.15.0
```

```
import os

import yaml
from cdktf import App
from cdktf import AzurermBackend
from cdktf import TerraformStack
from constructs import Construct
from imports.github import DataGithubTeam
from imports.github import GithubProvider
from imports.github import Repository
from imports.github import TeamRepository
```

Job that executes the pre-commit check
```
jobs:
  code_checks:
    executor: python
    steps:
      - run:
          name: Install pre-commit
          command: pip install pre-commit
      - checkout
      - restore_cache:
          keys:
            - pre-commit-cache-v1-{{ checksum ".pre-commit-config.yaml" }}

      - run:
          name: Code checks
          command: pre-commit run -a

      - save_cache:
          key: pre-commit-cache-v1-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
```
