### ISSUE TITLE
Support for pyi files now types_or is implemented

### ISSUE THREAD

**Issue by Greedquest** [asottile/reorder_python_imports#247]
Further to #103 which was closed at the time.

Would it be possible to update the pre-commit hooks for this repo to allow it to run by default on pyi files?

**Comment by Greedquest** [comment]
Or alternatively is there a way to avoid this in my local config:
```yaml
hooks:
-   id: reorder-python-imports
    files: \.pyi?$
    types: []
```
... as using `types_or` e.g.:
```yaml
hooks:
-   id: reorder-python-imports
    types_or: [python, pyi]
```
... doesn't seem to do anything in the `.pre-commit-config.yaml`. Does this setting only work for the hooks config, not the client side one?

**Comment by MarcoGorelli** [comment]
@Greedquest you'll also have to override `types`, e.g. I think this should work:
```
hooks:
-   id: reorder-python-imports
    types_or: [python, pyi]
    types: [text]  # overwrite types: [python]
```
