### ISSUE TITLE
reorder_python_imports suggests different order for py27 and py36

### ISSUE THREAD

**Issue by mikeecb** [asottile/reorder_python_imports#34]
I'm trying to run reorder_python_imports against a package that supports python 2.7 and python 3.6. I'm using [pre-commit](https://github.com/pre-commit/pre-commit) to do this and am first running reorder_python_imports against python 2.7 and then python 3.6. 

I'm running into issues because reorder_python_imports suggests different orderings for some imports. See below.

**Python 2.7**
```
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import logging

import enum

from y...
```

**Python 3.6**
```
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import enum
import logging

from y...
```

The enum package used is [enum34](https://pypi.python.org/pypi/enum34) v1.1.6.

**Comment by asottile** [comment]
This is because in python2.7 `enum` is a third party package, but in python3.6, it is a stdlib module.

For pre-commit, I'd suggest using [`language_version`](https://pre-commit.com/#overriding-language-version) to select `python3.6` so you get a consistent sorting based on `enum` being in the stdlib.

Here's an example (though this was written to disambiguate `argparse` between python2.6 and python2.7 -- now irrelevant since pre-commit no longer supports end-of-lifed pythons): https://pre-commit.com/#overriding-language-version

In your case:

```yaml
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
```
