### ISSUE TITLE
Use different seperator for application directories

### ISSUE THREAD

**Issue by timonbimon** [asottile/reorder_python_imports#60]
Hi again :) 

Is it possible to use a seperator other than ':' for the application directories.
The colon does not seem to play well with the .pre-commit-config.yaml

For the following .-pre-commit-config.yaml

```
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
    - id: reorder-python-imports
      args: [--application-directories=.:src]
      language_version: python3.7
```

I get the following error:

```
An error has occurred: InvalidConfigError: 
==> File /Users/timon/code/luminovo/project/.pre-commit-config.yaml
=====> while scanning a plain scalar
  in "<unicode string>", line 6, column 14:
          args: [--application-directories=.:src]
                 ^
found unexpected ':'
  in "<unicode string>", line 6, column 41:
     ... gs: [--application-directories=.:src]
                                         ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
```
