### ISSUE TITLE
Not clear how to use multiple application directories

### ISSUE THREAD

**Issue by davidism** [asottile/reorder_python_imports#71]
I'm trying to apply reorder-python-imports to [Werkzeug](https://github.com/pallets/werkzeug), and eventually automate it with a pre-commit config.

There are multiple directories that act as source roots: `src/` contains the `werkzeug` package, `examples/` contains various example packages and modules. I tried `reorder-python-imports --application-directory=src:examples`, but this produced the equivalent of not using `--application-directory` at all: `werkzeug` wasn't sorted last under `src`, and the example package names weren't sorted last under `examples`. Specifying only one directory sorted that directory correctly but not the other.

From the current docs, I couldn't tell if I was using `--application-directories` incorrectly, so I'm not sure if this is an issue with me or the library.

**Comment by asottile** [comment]
From the readme:

> (note: multiple paths are separated using a `:`).

Looking at the layout of `werkzeug` (it doesn't appear to be using `./src` layout) I think you probably want:

```bash
--application-directories .:examples
```

**Comment by davidism** [comment]
Sorry, I have a branch I'm working on where I moved to `src`, was about to edit the op with the correct link: https://github.com/pallets/werkzeug/tree/code-style

**Comment by asottile** [comment]
I see, in that case you probably want `.:src:examples`

**Comment by davidism** [comment]
Hmm, I think `src:examples` actually worked, but not the way I expected. It's treating both `werkzeug` and the package under `examples` as sorting in the same group, when I wanted stuff under `examples` to treat `werkzeug` as installed rather than local.

For reference, here's the command:

```
reorder-python-imports --application-directories src:examples **/*.py
```

And an example of the sorting in the `examples/cupoftee` package:

```python
import time
from os import path
from threading import Thread

from jinja2 import Environment
from jinja2 import PackageLoader

from cupoftee.db import Database
from cupoftee.network import ServerBrowser
from werkzeug.exceptions import HTTPException
from werkzeug.exceptions import NotFound
from werkzeug.middleware.shared_data import SharedDataMiddleware
from werkzeug.routing import Map
from werkzeug.routing import Rule
from werkzeug.wrappers import Request
from werkzeug.wrappers import Response
```

I want `werkzeug` to be at the same level as `jinja` in this case.

**Comment by asottile** [comment]
I see, so you want the examples to treat `werkzeug` as a third party

Yeah you can accomplish that with multiple entries of the hook, something like this? (untested, might need to tweak the regex)

```yaml
-   repo: https://github.com/asottile/reorder_python_imports
    rev: ...
    hooks:
    -   id: reorder-python-imports
        files: ^(?!examples/)
        args: [--application-directories, '.:src']
    -   id: reorder-python-imports
        files: ^examples/
        args: [--application-directories, examples]
```

the `.` is to make the imports inside `tests` sort correctly btw
