### ISSUE TITLE
Segmentation Fault when running pre-commit

### ISSUE THREAD

**Issue by timonbimon** [asottile/reorder_python_imports#86]
Hi there,

For some reason I get 

```
pre-commit run --all-files
[WARNING] Unexpected key(s) present on git://github.com/smian/pre-commit-makefile: sha
Reorder python imports...................................................make: *** [check] Segmentation fault: 11
```

when trying to run my pre-commit hooks with reorder_python_imports.

This is what my `.pre-commit-config.yaml` looks like:

```
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.6.1
  hooks:
  - id: reorder-python-imports
    args: [--application-directories=src]
    language_version: python3.7
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: flake8
    args: ['--ignore=E203,E266,E501,W503', '--max-line-length=88', '--max-doc-length=88', '--max-complexity=15', '--select=B,C,E,F,W,T4,B9']
    language_version: python3.7
- repo: git://github.com/smian/pre-commit-makefile
  sha: master
  hooks:
    - id: makefile-doc
```

If I comment out the reorder_python_imports, there is no segmentation fault...

Any ideas how to start debugging this?
